version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    restart: always

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    expose:
      - "9000"
    restart: no

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    networks:
      - inception
    volumes: 
      - mariadb:/var/lib/mysql
    env_file: 
      - .env
    expose:
      - "3306"
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/Katherine/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/Katherine/data/mariadb'

networks:
  inception:
    driver: bridge