version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    image: nginx:42
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    image: wordpress:42
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    expose:
      - "9000"
    restart: on-failure

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    image: mariadb:42
    networks:
      - inception
    volumes: 
      - mariadb_data:/var/lib/mysql
    env_file: 
      - .env
    expose:
      - "3306"
    restart: unless-stopped

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/kyang/data/wordpress'
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/kyang/data/mariadb'

networks:
  inception:
    driver: bridge