version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
  
  maria_db:
    build: requirements/mariadb/.
    container_name: mariadb
    env_file: 
      - .env
    